### ISSUE TITLE
[Bug] triggering the accent option for a (probably other keys as well) but then closing it makes only this possible to write afterwards:

### ISSUE THREAD

**Issue by OffifialMITX** [VladThodo/behe-keyboard#12]
```
ç΅ˆ¨
# ßç˜
``` 
just figured out that it is because alt is pressed but not released.

**Comment by VladThodo** [comment]
So, can I declare this closed? As it is irrelevant because you've said it's due to the ALT key being triggered.

**Comment by OffifialMITX** [comment]
If it's not the case anymore, sure!

On August 17, 2017 10:16:33 PM GMT+02:00, Vlad Todosin <notifications@github.com> wrote:
>So, can I declare this closed? As it is irrelevant because you've said
>it's due to the ALT key being triggered.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/VladThodo/behe-keyboard/issues/12#issuecomment-323182160

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
