### ISSUE TITLE
[FR] Add a gamepad function.

### ISSUE THREAD

**Issue by CrimsonFork** [VladThodo/behe-keyboard#14]
Seeing the arrow menu reminded me that there is no gampad app on F-Droid and having a gamepad which I don't have to switch the keyboard for first would be really great.

**Comment by noxarivis** [comment]
no,

this is a keyboard  for simple manner
I highly disagree to add useless trash

**Comment by noxarivis** [comment]
This is a programming and hacking keyboard.
such bloated function is misplaced here

besides, what trashy game doesn't have a gamepad in the game.

**Comment by OffifialMITX** [comment]
For example every game which is ported from it's pc version, but yeah, ypu're actually right about the aim of this app.

On August 24, 2017 1:23:48 PM GMT+02:00, noxarivis <notifications@github.com> wrote:
>This is a programming and hacking keyboard.
>such bloated function is misplaced here
>
>besides, what trashy game doesn't have a gamepad in the game.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/VladThodo/behe-keyboard/issues/14#issuecomment-324608187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by noxarivis** [comment]
My default, preinstalled Android keyboard has a freaking incognito mode.... I'm so annoyed by keyboards doing useless trash

**Comment by OffifialMITX** [comment]
What doe incognito mode do?

On August 25, 2017 10:06:21 AM GMT+02:00, noxarivis <notifications@github.com> wrote:
>My default, preinstalled Android keyboard has a freaking incognito
>mode.... I'm so annoyed by keyboards doing useless trash
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/VladThodo/behe-keyboard/issues/14#issuecomment-324851962

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by noxarivis** [comment]
It doesn't send every keystroke to fucking google

**Comment by OffifialMITX** [comment]
Yeah, it sends it directly to the NSA ;-P

On August 26, 2017 11:57:17 AM GMT+02:00, noxarivis <notifications@github.com> wrote:
>It doesn't send every keystroke to fucking google
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/VladThodo/behe-keyboard/issues/14#issuecomment-325109884

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
