### ISSUE TITLE
MissingTranslation build error

### ISSUE THREAD

**Issue by mimi89999** [VladThodo/behe-keyboard#17]
@VladThodo When we build release on F-Droid, we get MissingTranslation lint error: https://f-droid.org/wiki/page/com.vlath.keyboard/lastbuild_104

You could add:
```
android {
 lintOptions{
        disable 'MissingTranslation'
    }
}
```
to ignore them.

**Comment by VladThodo** [comment]
It's another fault of mine. That's what happens when you do things on hurry. I'll fix that tomorrow, as I can't simply disable the check in lint options because that will cause the app to crash on the devices that are set in that certain language.

**Comment by VladThodo** [comment]
I've updated the code. Does it generate any error now?

**Comment by mimi89999** [comment]
@VladThodo Could you please move the tag? Also the commit before the one changing version is tagged...

**Comment by VladThodo** [comment]
Done.
