### ISSUE TITLE
Arrow Key Hold

### ISSUE THREAD

**Issue by RSCipher001** [VladThodo/behe-keyboard#2]
If I hold any arrow key for 2 seconds or more then after releasing key my cursor won't stop, It'll go to the start of line

**Comment by VladThodo** [comment]
I figured out the cause of the bug, it was the `onLongPress(Key key)` method in `CustomKeyboard.java` that was always returning `true` instead of returning `super.onLongPress(Key key)`. With version 1.0.2, the bug is fixed so I think we can declare this closed.

**Comment by RSCipher001** [comment]
Great
