### ISSUE TITLE
Enter key does not work in some editors, it just hide the keyboard 

### ISSUE THREAD

**Issue by RigacciOrg** [VladThodo/behe-keyboard#22]
It seems that the BeHe keyboard does not assign the correct behaviour to the **Enter key** in different context.
The stock Android keyboard (6.0) adjust the Enter key action as **new line** or **confirm** or **search** according the context (text editor, form, search bar). The BeHe keyboard instead does not work well at least in some text editor. The Enter key does not make a newline in Jota Text Editor (from Google Play, nor into "Editor - Simple generic text editor" (from F-Droid); it just hide the keyboard itself. It acts like it was the "confirm" key in a form.
Strangely enough, the Enter key works well into the Termux teminal.
I installed BeHe Keyboard 1.0.5 from F-Droid, into an Android 6.0 chinese phone.

**Comment by VladThodo** [comment]
@RigacciOrg have you tried the latest version (1.1.2)?

**Comment by RigacciOrg** [comment]
Hi, I just tried version 1.1.2 from Google Play.
The issue seems to be fixed, at least in Jota Text Editor (but Jota is still affected by bug #23). Termux and K9-Mail are OK too.

**Comment by VladThodo** [comment]
I guess we can declare this fixed. I'll keep #23 open and see what I can do about that.
