### ISSUE TITLE
I propose a memorable logo

### ISSUE THREAD

**Issue by jol09** [VladThodo/behe-keyboard#40]
I'm Zulhelmi,
I work as a graphic designer,
I want to offer a new logo for

**BeHe Keyboard**.

I want to offer a modern and memorable logo, but I need permission to start working, please give me permission. This is just one logo, there are several versions that I will make. I beg your permission, and I will soon complete this design task,

![behe png](https://user-images.githubusercontent.com/36205466/37826507-469dbbd6-2ec6-11e8-9685-8fd183be0d55.png)

I hope you allow me to complete the design I have started.

**Comment by VladThodo** [comment]
BeHe will keep it's current logo. It's beautiful and it suits the material theme.
