### ISSUE TITLE
Number keys on standard layout remains the same even after disenabling it

### ISSUE THREAD

**Issue by Olamatto** [VladThodo/behe-keyboard#55]
#### Expected behavior
The number keys on standard layout, ought not to show again after disenabling it on the application settings.

#### Actual Behavior 
Number keys on standard layout, still shows even after disenabling it, after click the option menu on the keyboard.

#### How to reproduce
- Download and install the application [here](https://play.google.com/store/apps/details?id=com.vlath.keyboard)
- Lunch the application 
- Click on enable, enable BeHe keyboard, then click ok
- Press back
- Click on select 
- Choose BeHe Keyboard 
- Click on settings, disable Number keys on standard layout
- Press back
- On the test box, type some words
- Click on the option in the keyboard 
- Click on it again

And the number on keys comes back automatically. 

<hr>

Application version: 1.1.3
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/ZQ9nGQrL2PE

**Comment by sivaraam** [comment]
The numbers always appear in the **programming mode** of the keyboard. You only disabled numbers in the **standard mode**.

**Comment by VladThodo** [comment]
@Olamatto, as mentioned before, the programming mode has numbers on it by default and you can't disable it. The setting says "number keys on standard layout" so I guess this can be closed.
